# Generated by Django 6.0.6 on 2026-06-10 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study_Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('files', models.FileField(upload_to='study_materials/')),
            ],
        ),
    ]
