# Generated by Django 6.0.6 on 2026-06-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addpanel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='study_materials',
            name='Category',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
