# Generated by Django 6.0.6 on 2026-06-11 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addpanel', '0002_study_materials_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study_materials',
            name='Category',
        ),
        migrations.AddField(
            model_name='study_materials',
            name='category',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
    ]
