# Generated by Django 6.0.6 on 2026-06-11 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addpanel', '0003_remove_study_materials_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('content', models.TextField()),
                ('images', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
