# Generated by Django 6.0.6 on 2026-06-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addpanel', '0004_eventalbum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/photos/')),
                ('desc', models.CharField(default='', max_length=255)),
                ('is_cover', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=4)),
                ('exam', models.CharField(max_length=255)),
                ('rank_desc', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='gallery/achievements/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
