# Generated by Django 6.0.6 on 2026-06-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addpanel', '0005_photo_studentachievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('small_discription', models.CharField(max_length=100)),
                ('fee', models.IntegerField()),
                ('starting_date', models.DateField(auto_now_add=True)),
                ('total_time', models.IntegerField()),
                ('full_information', models.TextField()),
            ],
        ),
    ]
