# Generated by Django 6.0.6 on 2026-06-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addpanel', '0006_allcourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allcourse',
            name='small_discription',
            field=models.CharField(max_length=500),
        ),
    ]
