# Generated by Django 6.0.6 on 2026-06-16 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addpanel', '0007_alter_allcourse_small_discription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allcourse',
            name='full_information',
        ),
        migrations.AddField(
            model_name='allcourse',
            name='info_coures',
            field=models.CharField(default='Not specified', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allcourse',
            name='info_fee',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allcourse',
            name='info_head',
            field=models.CharField(default=' ', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allcourse',
            name='info_study',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
