# Generated by Django 4.1.13 on 2026-06-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addpanel', '0008_remove_allcourse_full_information_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcourse',
            name='action',
            field=models.CharField(default='active', max_length=100),
        ),
    ]
