# Generated by Django 4.1.13 on 2026-06-19 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Addpanel', '0010_sitesettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SiteSettings',
            new_name='Profile',
        ),
    ]
