# Generated by Django 4.1.13 on 2026-06-20 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addpanel', '0011_rename_sitesettings_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study_materials',
            name='material_name',
            field=models.CharField(max_length=200),
        ),
    ]
