# Generated by Django 4.1.13 on 2026-06-20 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Addpanel', '0012_alter_study_materials_material_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Study_Materials',
        ),
    ]
