# Generated by Django 4.1.13 on 2026-06-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Addpanel', '0013_delete_study_materials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books_notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icons', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('files', models.FileField(upload_to='media')),
            ],
        ),
    ]
