# Generated by Django 4.1.13 on 2026-06-20 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Addpanel', '0014_books_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='books_notes',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Addpanel.allcourse'),
            preserve_default=False,
        ),
    ]
