# Generated by Django 4.1.13 on 2026-06-21 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Addpanel', '0015_books_notes_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allcourse',
            name='info_head',
        ),
    ]
