# Generated by Django 4.1.13 on 2026-06-21 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Addpanel', '0016_remove_allcourse_info_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allcourse',
            name='info_coures',
        ),
    ]
