# Generated by Django 4.1.13 on 2026-06-22 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Addpanel', '0017_remove_allcourse_info_coures'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AcademyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trained_students', models.IntegerField(default=0)),
                ('selected_officers', models.IntegerField(default=0)),
                ('active_batches', models.IntegerField(default=0)),
                ('years_excellence', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('about_faculty', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='faculty/')),
                ('years_experience', models.CharField(max_length=50)),
                ('students_guided', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Addpanel_faculty',
            },
        ),
        migrations.RemoveField(
            model_name='photo',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='is_cover',
        ),
        migrations.CreateModel(
            name='FacultyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150)),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Addpanel.faculty')),
            ],
            options={
                'db_table': 'Addpanel_faculty_reviews',
            },
        ),
    ]
